#ifndef SOL_CONFIG_HPP
#define SOL_CONFIG_HPP

#ifndef PRODUCTION
#define PRODUCTION 0
#endif

#ifndef SOL_USE_LUAU
#define SOL_USE_LUAU 1
#endif

#ifndef LUA_VERSION_NUM
#define LUA_VERSION_NUM 501
#endif

#ifndef SOL_LUA_BIT32_LIB
#define SOL_LUA_BIT32_LIB 0
#endif

#ifndef SOL_SAFE_STACK_CHECK
#define SOL_SAFE_STACK_CHECK (PRODUCTION ? 0 : 1)
#endif

#ifndef SOL_SAFE_GETTER
#define SOL_SAFE_GETTER (PRODUCTION ? 0 : 1)
#endif

#ifndef SOL_SAFE_USERTYPE
#define SOL_SAFE_USERTYPE (PRODUCTION ? 0 : 1)
#endif

#ifndef SOL_SAFE_REFERENCES
#define SOL_SAFE_REFERENCES (PRODUCTION ? 0 : 1)
#endif

#ifndef SOL_SAFE_FUNCTION_CALLS
#define SOL_SAFE_FUNCTION_CALLS (PRODUCTION ? 0 : 1)
#endif

#ifndef SOL_SAFE_PROXIES
#define SOL_SAFE_PROXIES (PRODUCTION ? 0 : 1)
#endif

#ifndef SOL_SAFE_NUMERICS
#define SOL_SAFE_NUMERICS (PRODUCTION ? 0 : 1)
#endif

#ifndef SOL_NO_CHECK_NUMBER_PRECISION
#define SOL_NO_CHECK_NUMBER_PRECISION (PRODUCTION ? 1 : 0)
#endif

#ifndef SOL_ALL_INTEGER_VALUES_FIT
#define SOL_ALL_INTEGER_VALUES_FIT (PRODUCTION ? 1 : 0)
#endif

#ifndef SOL_USE_UNSAFE_BASE_LOOKUP
#define SOL_USE_UNSAFE_BASE_LOOKUP (PRODUCTION ? 1 : 0)
#endif

#ifndef SOL_NO_COMPAT
#define SOL_NO_COMPAT 0
#endif

#ifndef SOL_USERTYPE_TYPE_BINDING_INFO
#define SOL_USERTYPE_TYPE_BINDING_INFO 0
#endif

#ifndef SOL_NOEXCEPT_FUNCTION_TYPE
#define SOL_NOEXCEPT_FUNCTION_TYPE 1
#endif

#endif // SOL_CONFIG_HPP
